# Store episodes, num_envs, num_steps and stuff here for use in other files:
params:
  environment_name: "Lift"
  robots: "Panda"
  num_envs: 16
  num_skills: 10

observations:
  use_eef_state: True

training_params:
  episodes: 2000
  num_steps: 1000
  log_parent_folder: 'runs/diayn_ur5e'
  model_save_folder: 'weights/diayn_ur5e'

evaluation_params:
  num_steps: 200

file_params:
  model_load_path: "weights/diayn_ur5e/4.pt"
  video_output_folder: "videos/diayn_ur5e"
  video_prefix_path: 'rl_video'